### ISSUE TITLE
Clean up and fixing

### ISSUE THREAD

**Issue by bjornborg** [cfsd/cfsd18-perception-detectcone#1]
There is some cleanup needed in the repository. The repo contains unnecessary files such as editor temp configurations, duplicates, and deprecated files.

The eigen lib is downloaded and installed through Dockerfile, while having the headerfiles in the repo. I suggest that we either lock the lib version by including the header files in the repo or only have it in the Dockerfile. Having both solutions would just make it ambiguous.

Tiny dnn library has broken some linkage and need to be fixed. See:
[link](https://github.com/chalmersfsd/cfsd18-perception-detectcone/blob/master/src/detectcone.cpp#L329)

**Comment by arbulgazar** [comment]
tiny_dnn fixed

**Comment by chrberger** [comment]
@arbulgazar: which PR or commit?

**Comment by arbulgazar** [comment]
@chrberger https://github.com/chalmersfsd/cfsd18-perception-detectcone/commit/00fd7ecf5cba6bcb47b2b35553923c03a03384fd

Working on cleanup and removing Eigen now

**Comment by chrberger** [comment]
@arbulgazar: great, thanks. Don't forget to submit as PR for the formal review, merge, release procedure

**Comment by arbulgazar** [comment]
@chrberger oh yes, will do that!
